### ISSUE TITLE
foreman run web fails

### ISSUE THREAD

**Issue by chrisallick** [heroku-examples/ruby-websockets-chat-demo#3]
Chriss-MacBook-Pro:ruby-websockets-chat-demo chrisallick$ foreman run web
/Users/chrisallick/.rvm/gems/ruby-2.0.0-p451/gems/puma-2.6.0/lib/puma/cli.rb:272:in `parse_options': missing argument: -p (OptionParser::MissingArgument)
    from /Users/chrisallick/.rvm/gems/ruby-2.0.0-p451/gems/puma-2.6.0/lib/puma/cli.rb:418:in`run'
    from /Users/chrisallick/.rvm/gems/ruby-2.0.0-p451/gems/puma-2.6.0/bin/puma:10:in `<top (required)>'
    from /Users/chrisallick/.rvm/gems/ruby-2.0.0-p451/bin/puma:23:in`load'
    from /Users/chrisallick/.rvm/gems/ruby-2.0.0-p451/bin/puma:23:in `<main>'
    from /Users/chrisallick/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in`eval'
    from /Users/chrisallick/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'

**Comment by vinny1575** [comment]
same here. whats going on?

**Comment by dstsay** [comment]
Also getting same problem - any answers out there?

**Comment by opsb** [comment]
You need to run it with a port specified, e.g.

```
PORT=3005 foreman run web
```

then you'll hit the next problem...

**Comment by opsb** [comment]
Got it running with

```
REDISCLOUD_URL=localhost:6379 PORT=3005 foreman run web
```

you need to have redis running (brew install redis for mac)

**Comment by tohyongcheng** [comment]
thanks @opsb. got it running with your instructions.

**Comment by hone** [comment]
I've added a `.env.sample` to get people started.
